name: Payload update
on:
  repository_dispatch:
    types: [payload_update]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd ${{ secrets.PATH }}
            git pull
            yarn prod astro
